/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as PracticaRouteImport } from './routes/practica'
import { Route as ParcheRouteImport } from './routes/parche'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as CursoRouteImport } from './routes/curso'
import { Route as CheatSheetRouteImport } from './routes/cheat-sheet'
import { Route as BlueTeamRouteImport } from './routes/blue-team'
import { Route as AdcsRouteImport } from './routes/adcs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VectorVectorIdRouteImport } from './routes/vector.$vectorId'

const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticaRoute = PracticaRouteImport.update({
  id: '/practica',
  path: '/practica',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheRoute = ParcheRouteImport.update({
  id: '/parche',
  path: '/parche',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoRoute = CursoRouteImport.update({
  id: '/curso',
  path: '/curso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatSheetRoute = CheatSheetRouteImport.update({
  id: '/cheat-sheet',
  path: '/cheat-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueTeamRoute = BlueTeamRouteImport.update({
  id: '/blue-team',
  path: '/blue-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdcsRoute = AdcsRouteImport.update({
  id: '/adcs',
  path: '/adcs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VectorVectorIdRoute = VectorVectorIdRouteImport.update({
  id: '/vector/$vectorId',
  path: '/vector/$vectorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adcs': typeof AdcsRoute
  '/blue-team': typeof BlueTeamRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/curso': typeof CursoRoute
  '/decision': typeof DecisionRoute
  '/mapa': typeof MapaRoute
  '/parche': typeof ParcheRoute
  '/practica': typeof PracticaRoute
  '/tabla': typeof TablaRoute
  '/vector/$vectorId': typeof VectorVectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adcs': typeof AdcsRoute
  '/blue-team': typeof BlueTeamRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/curso': typeof CursoRoute
  '/decision': typeof DecisionRoute
  '/mapa': typeof MapaRoute
  '/parche': typeof ParcheRoute
  '/practica': typeof PracticaRoute
  '/tabla': typeof TablaRoute
  '/vector/$vectorId': typeof VectorVectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adcs': typeof AdcsRoute
  '/blue-team': typeof BlueTeamRoute
  '/cheat-sheet': typeof CheatSheetRoute
  '/curso': typeof CursoRoute
  '/decision': typeof DecisionRoute
  '/mapa': typeof MapaRoute
  '/parche': typeof ParcheRoute
  '/practica': typeof PracticaRoute
  '/tabla': typeof TablaRoute
  '/vector/$vectorId': typeof VectorVectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adcs'
    | '/blue-team'
    | '/cheat-sheet'
    | '/curso'
    | '/decision'
    | '/mapa'
    | '/parche'
    | '/practica'
    | '/tabla'
    | '/vector/$vectorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adcs'
    | '/blue-team'
    | '/cheat-sheet'
    | '/curso'
    | '/decision'
    | '/mapa'
    | '/parche'
    | '/practica'
    | '/tabla'
    | '/vector/$vectorId'
  id:
    | '__root__'
    | '/'
    | '/adcs'
    | '/blue-team'
    | '/cheat-sheet'
    | '/curso'
    | '/decision'
    | '/mapa'
    | '/parche'
    | '/practica'
    | '/tabla'
    | '/vector/$vectorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdcsRoute: typeof AdcsRoute
  BlueTeamRoute: typeof BlueTeamRoute
  CheatSheetRoute: typeof CheatSheetRoute
  CursoRoute: typeof CursoRoute
  DecisionRoute: typeof DecisionRoute
  MapaRoute: typeof MapaRoute
  ParcheRoute: typeof ParcheRoute
  PracticaRoute: typeof PracticaRoute
  TablaRoute: typeof TablaRoute
  VectorVectorIdRoute: typeof VectorVectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practica': {
      id: '/practica'
      path: '/practica'
      fullPath: '/practica'
      preLoaderRoute: typeof PracticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parche': {
      id: '/parche'
      path: '/parche'
      fullPath: '/parche'
      preLoaderRoute: typeof ParcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso': {
      id: '/curso'
      path: '/curso'
      fullPath: '/curso'
      preLoaderRoute: typeof CursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheat-sheet': {
      id: '/cheat-sheet'
      path: '/cheat-sheet'
      fullPath: '/cheat-sheet'
      preLoaderRoute: typeof CheatSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blue-team': {
      id: '/blue-team'
      path: '/blue-team'
      fullPath: '/blue-team'
      preLoaderRoute: typeof BlueTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adcs': {
      id: '/adcs'
      path: '/adcs'
      fullPath: '/adcs'
      preLoaderRoute: typeof AdcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vector/$vectorId': {
      id: '/vector/$vectorId'
      path: '/vector/$vectorId'
      fullPath: '/vector/$vectorId'
      preLoaderRoute: typeof VectorVectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdcsRoute: AdcsRoute,
  BlueTeamRoute: BlueTeamRoute,
  CheatSheetRoute: CheatSheetRoute,
  CursoRoute: CursoRoute,
  DecisionRoute: DecisionRoute,
  MapaRoute: MapaRoute,
  ParcheRoute: ParcheRoute,
  PracticaRoute: PracticaRoute,
  TablaRoute: TablaRoute,
  VectorVectorIdRoute: VectorVectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
